# Generated by Django 4.1.4 on 2022-12-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=50)),
                ("logo", models.ImageField(blank=True, upload_to="exam/logo")),
                ("details", models.TextField()),
                ("link", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("points", models.IntegerField()),
                ("brochure", models.FileField(blank=True, upload_to="exam/brochure")),
                ("eligibility", models.CharField(max_length=50)),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
