from rest_framework.decorators import api_view
from rest_framework.response import Response

@api_view(['GET'])
def apiOverview(request):
    apiUrls={
        'AUTHENTICATION' : ' ',
        # account/ password/reset/ [name='rest_password_reset']
        'rest_password_reset        ' : 'user/password/reset/',
        'rest_password_reset_confirm' : 'user/password/reset/confirm/',
        'rest_login                 ' : 'user/login/',
        'rest_logout                ' : 'user/logout/',
        'rest_user_details          ' : 'user/user/',
        'rest_password_change       ' : 'user/password/change/',
        'Registration               ' : 'user/signup/',
        'google_login               ' : 'user/google/',
        
        # User details 
        "List-all users (Admin only)" : "user/student/list/",
        "Add"                         : "user/student/add/",
        "List"                        : "user/student/details/",
        "Update"                      : "user/student/updateDetails/",
        "Delete"                      : "user/student/deleteDetails/",
        #Seperate users
        "Add activity points"         : "user/student/addActivity/",
        
        # Event views (admin only)
        # worshop <--> lecture < competitions-->
        # currId is a url parameter(id of the element generated by default)
        "List-all (Isauth)"           : 'workshop/list/',
        "List (Isauth)"               : 'workshop/details/<currId>',
        "Add"                         : 'workshop/add/',
        "Update"                      : 'workshop/update/<currId>',
        "Delete"                      : 'workshop/delete/<currId>',
        "Interest Filtering"          : "workshop/filter/", # {"interest":["AI", "DS", "BS"] }     
        
        
        'about   ' : 'about/',
        
        'admin   ' : 'admin/'  
    }
    return Response(apiUrls)