# Generated by Django 4.1.4 on 2022-12-10 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="facultyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_card", models.ImageField(blank=True, upload_to="faculty/idcard")),
                (
                    "dept",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("ME", "Mechanical"),
                            ("EC", "Electronics"),
                            ("EEE", "Electrical"),
                            ("CH", "Chemical"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "inst_id",
                    models.CharField(
                        choices=[
                            ("tkm124", "TKM College of Engineering"),
                            ("cet124", "College of Engineering Trivandrum"),
                            ("gect123", "GEC Thrissur"),
                            ("geck125", "GEC Kannur"),
                            ("rgr156", "Rajagiri School of Engineering and Technology"),
                            ("gecbrt76", "Government Engineering College, Barton Hill"),
                            ("mace123", "MACE Kothamangalam"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="promoterDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="promoter/logo")),
                ("link", models.URLField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="studentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_no", models.CharField(max_length=12)),
                ("course", models.CharField(blank=True, max_length=50)),
                (
                    "clas",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=2
                    ),
                ),
                ("avatar", models.ImageField(blank=True, upload_to="student")),
                (
                    "interest",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("DS", "Data Science"),
                            ("AI", "Artificial Intelligence"),
                            ("BS", "Business"),
                            ("DES", "Design"),
                            ("ES", "Embedded system"),
                        ],
                        max_length=500,
                    ),
                ),
                ("rollno", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="userDetail",),
    ]
