# Generated by Django 4.1.4 on 2022-12-10 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_facultydetails_promoterdetails_studentdetail_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="facultyDetails", new_name="facultyDetail",),
        migrations.RenameModel(old_name="promoterDetails", new_name="promoterDetail",),
    ]
