# Generated by Django 4.1.4 on 2022-12-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_studentdetail_inst"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdetail",
            name="credit_ac",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentdetail",
            name="credit_es",
            field=models.IntegerField(default=0),
        ),
    ]
