# Generated by Django 4.1.4 on 2022-12-09 16:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("provider", models.CharField(max_length=50)),
                ("logo", models.ImageField(blank=True, upload_to="scholarship/logo")),
                ("details", models.TextField()),
                ("link", models.CharField(max_length=100)),
                ("income_eligibility", models.IntegerField()),
                (
                    "program_eligibility",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("BT", "BTech"),
                            ("BR", "BArch"),
                            ("DI", "Diploma"),
                            ("O", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "category_eligibility",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("G", "General"),
                            ("SC", "SC"),
                            ("ST", "ST"),
                            ("OBC", "Other backward Classes"),
                            ("EWS", "Economically Weaker Section"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "gender_eligibility",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=100
                    ),
                ),
            ],
        ),
    ]
