# Generated by Django 4.1.4 on 2022-12-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_competition_brochure_alter_competition_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="mode",
            field=models.CharField(
                choices=[("Online", "Online"), ("Offline", "Offline")],
                default="Online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="mode",
            field=models.CharField(
                choices=[("Online", "Online"), ("Offline", "Offline")],
                default="Online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="mode",
            field=models.CharField(
                choices=[("Online", "Online"), ("Offline", "Offline")],
                default="Online",
                max_length=20,
            ),
        ),
    ]
