# Generated by Django 4.1.4 on 2022-12-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_studentdetail_inst"),
        ("events", "0003_competition_mode_lecture_mode_workshop_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField()),
                ("certificate", models.FileField(upload_to="certificate")),
            ],
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Worshop", "Worshop"),
                            ("Lecture", "Lecture"),
                            ("Competition", "Competition"),
                        ],
                        max_length=50,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("cert_field", models.ManyToManyField(to="events.certificate")),
                (
                    "students",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.studentdetail",
                    ),
                ),
            ],
        ),
    ]
