# Generated by Django 4.1.4 on 2022-12-10 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0005_certificate_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="students",
            field=models.OneToOneField(
                blank=True,
                default=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="students",
            field=models.OneToOneField(
                blank=True,
                default=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
