# Generated by Django 4.1.4 on 2022-12-10 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0006_certificate_students_alter_point_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="students",
            field=models.ForeignKey(
                blank=True,
                default=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
