# Generated by Django 4.1.4 on 2022-12-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_certificate_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="category",
            field=models.CharField(
                choices=[
                    ("DS", "Data Science"),
                    ("AI", "Artificial Intelligence"),
                    ("BS", "Business"),
                    ("DES", "Design"),
                    ("ES", "Embedded system"),
                ],
                default="AI",
                max_length=50,
            ),
        ),
    ]
