# Generated by Django 4.1.4 on 2022-12-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_workshop_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="category",
            field=models.CharField(
                choices=[
                    ("DS", "Data Science"),
                    ("AI", "Artificial Intelligence"),
                    ("BS", "Business"),
                    ("DES", "Design"),
                    ("ES", "Embedded system"),
                ],
                default="AI",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="category",
            field=models.CharField(
                choices=[
                    ("DS", "Data Science"),
                    ("AI", "Artificial Intelligence"),
                    ("BS", "Business"),
                    ("DES", "Design"),
                    ("ES", "Embedded system"),
                ],
                default="AI",
                max_length=50,
            ),
        ),
    ]
